### ISSUE TITLE
Export 8x1G ports via kernel driver

### ISSUE THREAD

**Issue by pstavirs** [QXIP/EXA8#14]
As per https://github.com/QXIP/EXA8/wiki/EXA8-Network, inserting the `mv88e6xxx.ko` module should put the 8x1G ports on the exa8 under the kernel dsa driver and `ifconfig` should show the `lan1`-`lan8` ports, but it's not working for me. The module in inserted fine as seen in `lsmod` and no error messages are seen on `dmesg`. 

The `mv88e6xxx.ko` that shipped alongwith the exa8 is same as the _legacy_ one in this repo - confirmed by using md5 on both files.

Any clues?

**Comment by pstavirs** [comment]
I was able to figure this out.

Looking at the device tree on the running box, I saw that there are two devices `/soc/pci/mrml-bridge0/mdio-nexus/mdio1/switch0` and `/switch` in the tree representing the same 8 port eth switch. The former uses the standard kernel driver whereas the latter uses `mvmvdio_uio.ko` which I assume is a Cubro proprietary driver using DPDK. The device tree had the kernel device set to _status disabled_ while the UIO device was set to _status okay_. This was setup in uboot env variable `fdt_update`. Changing that environment variable to enable the kernel device was all it needed.

**Comment by lmangani** [comment]
@pstavirs thanks for sharing this back! Is there any steps you can share here so i can extend the docs to make this easilier for the next guy?

**Comment by pstavirs** [comment]
Here are the instructions -

Dump the current value of the uboot `fdt_update` variable -

```
$ sudo fw_printenv | grep fdt_update
fdt_update=fdt adds ${fdtcontroladdr};fdt resize 4096;fdt set /soc/pci/mrml-bridge0/mdio-nexus/mdio1 phandle <0x4e>;fdt set /soc/pci/mrml-bridge0/mdio-nexus/mdio1/switch0 status disabled;fdt mknode / switch;fdt set /switch compatible marvell,mvmdio-uio;fdt set /switch status okay;fdt set /switch mii-bus <0x4e>
```

The above output is from my exa8. Yours might be different. The important thing to note is the `/soc/pci/mrml-bridge0/mdio-nexus/mdio1/switch0` which is the device that the kernel has a driver for is set to `status disabled` and `/switch` (which I assume has a Cubro proprietary driver) is set to `status okay`. We need to swap the status for those two devices.

To do that, update that variable swapping the status values -
```
$ sudo fw_setenv fdt_update fdt adds ${fdtcontroladdr};fdt resize 4096;fdt set /soc/pci/mrml-bridge0/mdio-nexus/mdio1 phandle <0x4e>;fdt set /soc/pci/mrml-bridge0/mdio-nexus/mdio1/switch0 status okay;fdt mknode / switch;fdt set /switch compatible marvell,mvmdio-uio;fdt set /switch status disabled;fdt set /switch mii-bus <0x4e>
```

Reboot the device and use `sudo fw_printenv | grep fdt_update` to verify that the change is reflecting.

Use `ifconfig -a` to verify that the `lan[1-8]` devices are created. If they are down, use `ifconfig lan[1-8] up` to enable them. You will also need to enable the CPU port `ifconfig enp5s0f1 up` for the `lan[1-8]` devices to come up.

**Comment by lmangani** [comment]
Thanks and best of luck with the contest! ;)
